import type { RobloxVNode } from "../../shared/types";

const SUPPORTED_CLASSES = new Set([
  "Frame",
  "CanvasGroup",
  "TextLabel",
  "TextButton",
  "TextBox",
  "ImageLabel",
  "ImageButton",
  "ScrollingFrame",
  "VideoFrame",
  "ViewportFrame",
  "UICorner",
  "UIStroke",
  "UIPadding",
  "UIListLayout",
  "UIGridLayout",
  "UIPageLayout",
  "UITableLayout",
  "UIGradient",
  "UIAspectRatioConstraint",
  "UISizeConstraint",
  "UITextSizeConstraint",
  "UIScale",
  "UIFlexItem",
  "UIDragDetector",
]);

const SUPPORTED_PROPS = new Set([
  "Active",
  "Ambient",
  "AnchorPoint",
  "Animated",
  "ApplyStrokeMode",
  "AspectRatio",
  "AutomaticCanvasSize",
  "AutomaticSize",
  "BackgroundColor3",
  "BackgroundTransparency",
  "BorderMode",
  "BorderColor3",
  "BorderOffset",
  "BorderSizePixel",
  "BorderStrokePosition",
  "BottomLeftRadius",
  "BottomRightRadius",
  "CanvasSize",
  "CanvasPosition",
  "CellPadding",
  "CellSize",
  "Circular",
  "ClearTextOnFocus",
  "ClipsDescendants",
  "Color",
  "CornerRadius",
  "EasingDirection",
  "EasingStyle",
  "Enabled",
  "FillDirectionMaxCells",
  "FillEmptySpaceColumns",
  "FillEmptySpaceRows",
  "FillDirection",
  "FlexMode",
  "GamepadInputEnabled",
  "GroupColor3",
  "GroupTransparency",
  "GrowRatio",
  "HorizontalFlex",
  "HorizontalAlignment",
  "HoverImage",
  "Image",
  "ImageColor3",
  "ImageRectOffset",
  "ImageRectSize",
  "ImageTransparency",
  "Interactable",
  "ItemLineAlignment",
  "LayoutOrder",
  "LightColor",
  "LineHeight",
  "LineJoinMode",
  "Looped",
  "MajorAxis",
  "MaxSize",
  "MaxTextSize",
  "MaxVisibleGraphemes",
  "MinSize",
  "MinTextSize",
  "MultiLine",
  "Offset",
  "Padding",
  "PaddingBottom",
  "PaddingLeft",
  "PaddingRight",
  "PaddingTop",
  "PlaceholderColor3",
  "PlaceholderText",
  "Playing",
  "Position",
  "PressedImage",
  "RichText",
  "Rotation",
  "Scale",
  "ScaleType",
  "ScrollBarImageColor3",
  "ScrollBarImageTransparency",
  "ScrollBarThickness",
  "ScrollWheelInputEnabled",
  "ScrollingDirection",
  "ScrollingEnabled",
  "Selectable",
  "SelectionOrder",
  "ShrinkRatio",
  "Size",
  "SizeConstraint",
  "SliceScale",
  "StartCorner",
  "StrokeSizingMode",
  "Text",
  "TextColor3",
  "TextEditable",
  "TextScaled",
  "TextSize",
  "TextStrokeColor3",
  "TextStrokeTransparency",
  "TextTransparency",
  "TextTruncate",
  "TextWrapped",
  "TextXAlignment",
  "TextYAlignment",
  "Thickness",
  "TileSize",
  "TopLeftRadius",
  "TopRightRadius",
  "TouchInputEnabled",
  "Transparency",
  "TweenTime",
  "Type",
  "VerticalAlignment",
  "VerticalFlex",
  "Video",
  "Visible",
  "Volume",
  "Wraps",
  "ZIndex",
]);

export function collectRendererWarnings(node: RobloxVNode): string[] {
  const warnings: string[] = [];
  visit(node, warnings);
  return warnings;
}

function visit(node: RobloxVNode, warnings: string[]): void {
  if (!SUPPORTED_CLASSES.has(node.className)) {
    warnings.push(`Unsupported class ${node.className}; rendering its children best-effort.`);
  }

  for (const key of Object.keys(node.props ?? {})) {
    if (!SUPPORTED_PROPS.has(key)) {
      warnings.push(`Unsupported ${node.className}.${key}; property was ignored.`);
    }
  }

  for (const child of node.children ?? []) {
    visit(child, warnings);
  }
}
